/*
DROP TABLE ESP_SQL_C6.ALUMNOS
*/

SELECT 
	ID,
	DOCUMENTO,
	NOMBRES
FROM ESP_SQL_C6.ALUMNOS
WHERE 
	ID IN (4,10,15)


USE ESP_SQL_MOD_BAS
SELECT * FROM ESP_SQL_MOD_BAS.ESP_SQL_C6.ALUMNOS

-- MOSTRAR VALORES UNICOS POR CAMPO
SELECT DISTINCT 
	FECHA_NACIMIENTO
FROM ESP_SQL_C6.ALUMNOS

-- MOSTRAR VALORES UNICOS POR TODA LA TABLA
SELECT DISTINCT 
	*
FROM ESP_SQL_MOD_BAS.ESP_SQL_C6.ALUMNOS

-- SELECT  * FROM {NOM_BD}.{NOM_SCHEMA}.{NOM_TABLA}
SELECT * FROM ESP_SQL_MOD_BAS.ESP_SQL_C6.ALUMNOS

SELECT * FROM BD_PROYECTOS.CLASES.PRUEBA

-- OPERACIONES ARITMETICAS
SELECT 
	*,
	EDAD + 5 AS EDAD_NUEVA,
	EDAD - 5 AS EDAD_ANTIGUA,
	EDAD * 2 AS EDAD_MULTIPLICADA,
	EDAD / 2.0 AS EDAD_DIVIDIDA,
	EDAD % 2 AS EDAD_RESIDUO
FROM ESP_SQL_MOD_BAS.ESP_SQL_C6.ALUMNOS;


-- OPERACIONES DE TEXTO
SELECT 
	ID,
	DOCUMENTO,
	APELLIDOS,	
	NOMBRES,
	TELF,
	UPPER(CORREO) AS CORREO,
	CAST(EDAD AS decimal(5,3)) AS EDAD,
	FECHA_NACIMIENTO,
	LOWER(APELLIDOS) AS APELLIDO_MINUSCULA,
	LEN(NOMBRES) AS LARGO_NOMBRES,
	LEFT(APELLIDOS,8) AS LEFT_APELLIDOS,
	RIGHT(APELLIDOS,5) AS RIGHT_APELLIDOS,
	REPLACE(APELLIDOS,'G','J') AS REEMPLAZO
FROM ESP_SQL_MOD_BAS.ESP_SQL_C6.ALUMNOS;

-- OPERACIONES CON FECHAS
SELECT GETDATE() --OBTENER LA FECHA Y HORA EN  ESTE INSTANTE

SELECT 
	*,
	DATEADD(DAY,3223,FECHA_NACIMIENTO) AS FECHA_AUMENTADA_DIAS,
	DATEADD(MONTH,3,FECHA_NACIMIENTO) AS FECHA_AUMENTADA_MES,
	DATEDIFF(DAY,FECHA_NACIMIENTO, GETDATE()) AS DIFERENCIA_DIAS,
	DAY(FECHA_NACIMIENTO) AS DIA_NACIMIENTO,
	MONTH(FECHA_NACIMIENTO) AS MES_NACIMIENTO,
	YEAR(FECHA_NACIMIENTO) AS ANIO_NACIMIENTO
FROM ESP_SQL_MOD_BAS.ESP_SQL_C6.ALUMNOS

-- WHERE 
SELECT 
	* 
FROM ESP_SQL_MOD_BAS.ESP_SQL_C6.ALUMNOS
WHERE
	--EDAD > 25
	--APELLIDOS LIKE '%GÁLVEZ%'
	--EDAD = 30
	--EDAD >= 22 AND EDAD <= 27
	--EDAD BETWEEN 22 AND 27
	--LEN(APELLIDOS)>15
	--DOCUMENTO LIKE '4%' AND EDAD > 22
	--DOCUMENTO LIKE '4%' OR EDAD > 22
	--DOCUMENTO NOT LIKE '4%' -- NEGACION DE EXPRESION REGULAR
	--EDAD != 30
	NOT(DOCUMENTO LIKE '4%' AND EDAD > 22)