--CREATE SCHEMA ESP_SQL_C5_E2
--GO

CREATE TABLE ESP_SQL_C5_E2.CONSORCIO(
	PK_CONSORCIO INT PRIMARY KEY IDENTITY(1,1),
	NOM_CONSORCIO VARCHAR(100) UNIQUE NOT NULL,
	FEC_FUNDACION DATE NOT NULL
)


CREATE TABLE ESP_SQL_C5_E2.AREA (
	PK_AREA INT PRIMARY KEY IDENTITY(1,1),
	NOM_AREA VARCHAR(100) UNIQUE NOT NULL,
	DES_AREA VARCHAR(100) NOT NULL
)

CREATE TABLE ESP_SQL_C5_E2.EMPRESA(
	PK_EMPRESA INT PRIMARY KEY IDENTITY(1,1),
	NOM_EMPRESA VARCHAR(50) UNIQUE NOT NULL,
	DES_EMPRESA VARCHAR(100),
	MISION VARCHAR(200),
	VISION VARCHAR(200),
	FEC_FUNDACION DATE,
	ESTADO_EMPRESA VARCHAR(20),
	FK_CONSORCIO INT FOREIGN KEY REFERENCES ESP_SQL_C5_E2.CONSORCIO(PK_CONSORCIO)
)

CREATE TABLE ESP_SQL_C5_E2.AREA_EMPRESA(
	PK_AREA_EMPRESA INT PRIMARY KEY IDENTITY(1,1),
	FEC_CREACION DATE NOT NULL,
	ESTADO_EMPRESA VARCHAR(200),
	FK_AREA INT FOREIGN KEY REFERENCES ESP_SQL_C5_E2.AREA(PK_AREA),
	FK_EMPRESA INT FOREIGN KEY REFERENCES ESP_SQL_C5_E2.EMPRESA(PK_EMPRESA)
)

CREATE TABLE ESP_SQL_C5_E2.EMPLEADO(
	PK_EMPLEADO INT PRIMARY KEY IDENTITY(1,1),
	DNI_EMPLEADO VARCHAR(100) UNIQUE NOT NULL,
	AP_EMPLEADO VARCHAR(100),
	AM_EMPLEADO VARCHAR(100),
	FEC_NACIMIENTO DATE,
	EDAD INT,
	FK_AREA_EMPRESA INT FOREIGN KEY REFERENCES ESP_SQL_C5_E2.AREA_EMPRESA(PK_AREA_EMPRESA)
)
GO
/*
	DROP TABLE ESP_SQL_C5_E2.EMPLEADO
	DROP TABLE ESP_SQL_C5_E2.AREA_EMPRESA
	DROP TABLE ESP_SQL_C5_E2.AREA
	DROP TABLE ESP_SQL_C5_E2.EMPRESA
	DROP TABLE ESP_SQL_C5_E2.CONSORCIO
*/

-- SP_RENAME
sp_rename 'ESP_SQL_C5_E2.EMPLEADO.DNI_EMPLEADO','DNI','COLUMN'