-- EJERCICIO 12
SELECT	STOCK,
	CASE
		WHEN STOCK < 3000 THEN 'DÉFICIT' -- WHEN STOCK BETWEEN 0 AND 3000 THEN 'DÉFICIT'
		WHEN STOCK BETWEEN 3000 AND 6000 THEN 'NORMAL'
		WHEN STOCK > 6000 THEN 'SUPERAVIT' -- WHEN STOCK < 6000 THEN 'SUPERAVIT'
	END AS RESULTADO_STOCK
FROM ESP_SQL_C7.PRODUCTO_ALMACEN

-- EJERCICIO 13

SELECT	
	CASE
		WHEN STOCK < 3000 THEN 'DÉFICIT' -- WHEN STOCK BETWEEN 0 AND 3000 THEN 'DÉFICIT'
		WHEN STOCK BETWEEN 3000 AND 6000 THEN 'NORMAL'
		WHEN STOCK > 6000 THEN 'SUPERAVIT' -- WHEN STOCK < 6000 THEN 'SUPERAVIT'
	END AS RESULTADO_STOCK,
		COUNT(1) AS CANTIDAD_REGISTRO
FROM ESP_SQL_C7.PRODUCTO_ALMACEN
GROUP BY
	CASE
		WHEN STOCK < 3000 THEN 'DÉFICIT' -- WHEN STOCK BETWEEN 0 AND 3000 THEN 'DÉFICIT'
		WHEN STOCK BETWEEN 3000 AND 6000 THEN 'NORMAL'
		WHEN STOCK > 6000 THEN 'SUPERAVIT' -- WHEN STOCK < 6000 THEN 'SUPERAVIT'
	END

-- EJERCICIO 14

DELETE FROM ESP_SQL_C7.PRODUCTO_ALMACEN 
	WHERE STOCK > 10000

	select * from ESP_SQL_C7.PRODUCTOS
	select * from ESP_SQL_C7.ALMACEN

-- EJERCICIO 15

UPDATE 
	PA 
	SET 
		STOCK='6000' 
	FROM ESP_SQL_C7.PRODUCTO_ALMACEN PA 
	INNER JOIN ESP_SQL_C7.PRODUCTOS P 
	ON 
		PA.FK_PRODUCTO= P.PK_PRODUCTO
	INNER JOIN ESP_SQL_C7.ALMACEN A 
	ON 
		PA.FK_ALMACEN= A.PK_ALMACEN
	WHERE 
		(P.NOM_PRODUCTO = 'MANZANAS') AND 
		(A.NOM_ALMACEN = 'ALM. ACHO')


SELECT * FROM ESP_SQL_C7.PRODUCTO_ALMACEN