
/*CREAR UN STORED PROCEDURE QUE ALMACENE EN UNA TABLA DISTINTA LA INFORMACIÓN DE CADA REGION
	VENTAS_EAST
	VENTAS_WEST
	VENTAS_CENTRAL
*/

CREATE PROCEDURE DISTRIBUIR_INFO AS
BEGIN
	-- VENTAS CENTRAL
	IF OBJECT_ID('ESP_SQL_MOD_BAS.dbo.VENTAS_CENTRAL') IS NULL
		SELECT 
			* 
		INTO ESP_SQL_MOD_BAS.dbo.VENTAS_CENTRAL
		FROM VENTAS 
		WHERE Region = 'Central'
	ELSE
		INSERT INTO ESP_SQL_MOD_BAS.dbo.VENTAS_CENTRAL
		SELECT 
			*
		FROM VENTAS
		WHERE 
			Region = 'Central'

	-- VENTAS WEST
	IF OBJECT_ID('ESP_SQL_MOD_BAS.dbo.VENTAS_WEST') IS NULL
		SELECT 
			* 
		INTO ESP_SQL_MOD_BAS.dbo.VENTAS_WEST
		FROM VENTAS 
		WHERE Region = 'West'
	ELSE
		INSERT INTO ESP_SQL_MOD_BAS.dbo.VENTAS_WEST
		SELECT 
			*
		FROM VENTAS
		WHERE 
			Region = 'West'

	-- VENTAS East
	IF OBJECT_ID('ESP_SQL_MOD_BAS.dbo.VENTAS_EAST') IS NULL
		SELECT 
			* 
		INTO ESP_SQL_MOD_BAS.dbo.VENTAS_EAST
		FROM VENTAS 
		WHERE Region = 'East'
	ELSE
		INSERT INTO ESP_SQL_MOD_BAS.dbo.VENTAS_EAST
		SELECT 
			*
		FROM VENTAS
		WHERE 
			Region = 'East'
END


EXEC DISTRIBUIR_INFO

SELECT * FROM ESP_SQL_MOD_BAS.dbo.VENTAS_EAST
SELECT * FROM ESP_SQL_MOD_BAS.dbo.VENTAS_WEST
SELECT * FROM ESP_SQL_MOD_BAS.dbo.VENTAS_CENTRAL