CREATE VIEW REGION_TRADUCIDA AS
SELECT 
	FECHA_ORDEN,
	CASE 
	WHEN Region = 'Central' THEN 'Centro'
	WHEN Region = 'East' THEN 'Este'
	ELSE
		'Oeste'
	END AS REGION_ES,
	VENDEDOR,
	PRODUCTO,
	UNIDADES * PRECIO AS INGRESO_TOTAL
FROM VENTAS


SELECT
	* 
FROM REGION_TRADUCIDA
WHERE 
	Vendedor = 'Jones'